### ISSUE TITLE
Face Tracker crashing OBS

### ISSUE THREAD

**Issue by dansternofbeyer** [norihiro/obs-face-tracker#174]
**Source/filter types**

- Face Tracker (filter)

**Describe the bug**

OBS crashes after a few hours of running the Face Tracker.

**To Reproduce**

1 : Add Face Tracker as a filter to a source, in my case a Video Capture Device that is pulling a feed from a webcam.
2 : Put your face in front of the camera. In my case a mannequin head as a stable test subject.
3 : Wait 2 hours and OBS will crash

**Expected behavior**

I expect OBS not to crash. I hope this can run continuously for at least 5 hours. Ideally never crashing if left on.

**Actual behavior**

OBS crashes after 2 hours. Sometimes less, sometimes a little more.

**Desktop (please complete the following information):**
 - OS: macOS, Monterey v12.1, Apple M1 chip
 - OBS Version: 31.1.2
 - Face Tracker Version: 0.7.2

**Additional context**

**Comment by norihiro** [comment]
Thank you for the report.
Could you possibly provide the crash report?

1. Open Console.app (Located in /Applications/Utilities).
2. Navigate to the Crash Reports view along the left sidebar, then sort the table by date to find the most recent crash with the OBS process name.
3. Drag and drop the selected crash to the comment below, or copy-and-paste the report text to the comment.
--

**Comment by dansternofbeyer** [comment]
number 4 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               OBS [535]
Path:                  /Applications/OBS.app/Contents/MacOS/OBS
Identifier:            com.obsproject.obs-studio
Version:               31.1.2 (16531765140)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2025-08-23 23:19:27.1344 -0600
OS Version:            macOS 12.1 (21C52)
Report Version:        12
Anonymous UUID:        D29B9F53-7738-7F6B-D0E6-54670A12DDB2


Time Awake Since Boot: 10000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x7ff0000000000010 -> 0xffff800000000010 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x7ff0000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [535]

VM Region Info: 0xffff800000000010 is not in any region.  Bytes after previous region: 18446497782568058897  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)
--->  
      UNUSED SPACE AT END

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobs-opengl.dylib                 0x124cf7250 __gl_update_block_invoke + 92
1   libobs-opengl.dylib                 0x124cf7248 __gl_update_block_invoke + 84
2   libdispatch.dylib                   0x1916f0e60 _dispatch_call_block_and_release + 32
3   libdispatch.dylib                   0x1916f2bac _dispatch_client_callout + 20
4   libdispatch.dylib                   0x1917010ac _dispatch_main_queue_callback_4CF + 944
5   CoreFoundation                       0x1919bdf00 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
6   CoreFoundation                       0x19197b8c0 __CFRunLoopRun + 2540
7   CoreFoundation                       0x19197a734 CFRunLoopRunSpecific + 600
8   HIToolbox                           0x19a50cf68 RunCurrentEventLoopInMode + 292
9   HIToolbox                           0x19a50ccdc ReceiveNextEventCommon + 552
10  HIToolbox                           0x19a50ca9c _BlockUntilNextEventMatchingListInModeWithFilter + 72
11  AppKit                               0x1944d0ce0 _DPSNextEvent + 844
12  AppKit                               0x1944cf584 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
13  AppKit                               0x1944c15a4 -[NSApplication run] + 596
14  libqcocoa.dylib                     0x10a9ae59c 0x10a998000 + 91548
15  QtCore                               0x104fd6cb0 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 596
16  QtCore                               0x104fcda18 QCoreApplication::exec() + 216
17  OBS                                 0x102558c1c 0x102460000 + 1018908
18  dyld                                 0x102b490f4 start + 520

Thread 1:: com.apple.CFSocket.private
0   libsystem_kernel.dylib               0x19187fd38 __select + 8
1   CoreFoundation                       0x1919a7334 __CFSocketManager + 648
2   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
3   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 2:: libobs: hotkey thread
0   libsystem_kernel.dylib               0x1918790c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib             0x1918b1808 _pthread_cond_wait + 1228
2   libobs                               0x102e16738 os_event_timedwait + 128
3   libobs                               0x102dc2138 obs_hotkey_thread + 168
4   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
5   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 3:: tiny_tubular_task_thread
0   libsystem_kernel.dylib               0x191875990 semaphore_wait_trap + 8
1   libobs                               0x102e169bc os_sem_wait + 20
2   libobs                               0x102e15078 tiny_tubular_task_thread + 200
3   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
4   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 4:: audio-io: audio thread
0   libsystem_kernel.dylib               0x191878ebc __semwait_signal + 8
1   libsystem_c.dylib                   0x191783d88 nanosleep + 216
2   libsystem_c.dylib                   0x191783ca4 usleep + 68
3   libobs                               0x102e0de60 os_sleepto_ns_fast + 100
4   libobs                               0x102d99614 audio_thread + 752
5   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
6   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 5:: video-io: video thread
0   libsystem_kernel.dylib               0x191875990 semaphore_wait_trap + 8
1   libobs                               0x102e169bc os_sem_wait + 20
2   libobs                               0x102d9d6e4 video_thread + 84
3   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
4   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 6:: libobs: graphics thread
0   libsystem_kernel.dylib               0x191878ebc __semwait_signal + 8
1   libsystem_c.dylib                   0x191783d88 nanosleep + 216
2   libobs                               0x102e0ddc4 os_sleepto_ns + 96
3   libobs                               0x102df6e58 obs_graphics_thread_loop + 6808
4   libobs                               0x102da5e8c obs_graphics_thread_loop_autorelease + 32
5   libobs                               0x102df7170 obs_graphics_thread + 168
6   libobs                               0x102da5e50 obs_graphics_thread_autorelease + 32
7   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
8   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 7:: scripting: defer
0   libsystem_kernel.dylib               0x191875990 semaphore_wait_trap + 8
1   libobs                               0x102e169bc os_sem_wait + 20
2   obs-scripting.dylib                 0x126091420 defer_thread + 56
3   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
4   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 8:: AMCP Logging Spool
0   libsystem_kernel.dylib               0x191875990 semaphore_wait_trap + 8
1   caulk                               0x19a27e8ac caulk::mach::semaphore::wait_or_error() + 28
2   caulk                               0x19a26165c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                               0x19a26127c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
5   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 9:: face-det
0   libsystem_kernel.dylib               0x1918790c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib             0x1918b1808 _pthread_cond_wait + 1228
2   obs-face-tracker                     0x127348bfc face_detector_base::thread_routine(void*) + 160
3   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
4   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 10:
0   libsystem_kernel.dylib               0x191878ebc __semwait_signal + 8
1   libsystem_c.dylib                   0x191783d88 nanosleep + 216
2   libsystem_c.dylib                   0x191783ca4 usleep + 68
3   CoreMediaIO                         0x19f17b564 CMIOGraph::OneOrMoreInputUnitsAreReadyToBePulled(bool&) + 732
4   CoreMediaIO                         0x19f17c184 CMIOGraph::DoWork(unsigned int) + 484
5   CoreMediaIO                         0x19f17ed00 CMIO::Thread::QueuedTWorkThread<unsigned int>::DoWork() + 180
6   CoreMediaIO                         0x19f1871c4 CMIO::Thread::SignaledThread::ThreadLoop() + 216
7   CoreMediaIO                         0x19f1870b0 CMIO::Thread::SignaledThread::WorkQueuedThreadCallback(void*) + 88
8   CoreMedia                           0x19a2a5a88 figThreadMain + 248
9   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
10  libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 11:: com.apple.NSEventThread
0   libsystem_kernel.dylib               0x191875954 mach_msg_trap + 8
1   libsystem_kernel.dylib               0x191875d00 mach_msg + 76
2   CoreFoundation                       0x19197ced8 __CFRunLoopServiceMachPort + 372
3   CoreFoundation                       0x19197b390 __CFRunLoopRun + 1212
4   CoreFoundation                       0x19197a734 CFRunLoopRunSpecific + 600
5   AppKit                               0x19463dc90 _NSEventThread + 196
6   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
7   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 12:: face-trk
0   libsystem_kernel.dylib               0x1918790c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib             0x1918b1808 _pthread_cond_wait + 1228
2   obs-face-tracker                     0x12737e718 face_tracker_base::thread_routine(void*) + 188
3   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
4   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 13:: face-trk
0   libsystem_kernel.dylib               0x1918790c0 __psynch_cvwait + 8
1   libsystem_pthread.dylib             0x1918b1808 _pthread_cond_wait + 1228
2   obs-face-tracker                     0x12737e718 face_tracker_base::thread_routine(void*) + 188
3   libsystem_pthread.dylib             0x1918b1240 _pthread_start + 148
4   libsystem_pthread.dylib             0x1918ac024 thread_start + 8

Thread 14:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib             0x1918ac010 start_wqthread + 0


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001546bd560   x1: 0x0000000000000000   x2: 0x00000000000220a8   x3: 0x0000000000000004
    x4: 0x0000000000040000   x5: 0x0000000000000019   x6: 0x0000000000000800   x7: 0x0000000000000000
    x8: 0x0000600000c6b040   x9: 0x7ff0000000000000  x10: 0x0000000000000002  x11: 0x00000000000120a8
   x12: 0x0000000000010001  x13: 0x0000000000001436  x14: 0x0000000000001436  x15: 0x00000001ea9202b0
   x16: 0x0000000217545fd8  x17: 0x000000021e8fc090  x18: 0x000000010b1dfd5c  x19: 0x00000001561b9a00
   x20: 0x0000000155121a00  x21: 0x0000600003557680  x22: 0x0000600003ad42c0  x23: 0x0000000000000114
   x24: 0x0000000000000000  x25: 0x0000000102bbc660  x26: 0x0000600003573a80  x27: 0x000000000000000f
   x28: 0x0000000002ffffff   fp: 0x000000016d99db40   lr: 0x177d000124cf7248
    sp: 0x000000016d99db20   pc: 0x0000000124cf7250 cpsr: 0x00001000
   far: 0x7ff0000000000010  esr: 0x92000004 (Data Abort) byte read Translation fault

Binary Images:
       0x124cf0000 -        0x124d33fff libobs-opengl.dylib (*) <361d1f0c-2786-3fd0-97e5-6da1abc7130b> /Applications/OBS.app/Contents/Frameworks/libobs-opengl.dylib
       0x1916ef000 -        0x191735fff libdispatch.dylib (*) <3a9e9a1e-72b6-3f66-aa17-d955384c1a39> /usr/lib/system/libdispatch.dylib
       0x1918f8000 -        0x191e3bfff com.apple.CoreFoundation (6.9) <f5ea9592-4ef9-3d35-b23d-5c21283acc52> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x19a4da000 -        0x19a809fff com.apple.HIToolbox (2.1.1) <01b981b8-a2d8-374d-9a0e-c4ac8c1009da> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
       0x19448f000 -        0x195342fff com.apple.AppKit (6.9) <a8bbc643-113d-310f-96b6-77a973bf2dba> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x10a998000 -        0x10aa3bfff libqcocoa.dylib (*) <62b55791-da21-30f4-946f-7cb71ad0de1a> /Applications/OBS.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x104f3c000 -        0x1053d3fff org.qt-project.QtCore (6.8) <35642b16-7f41-3e13-a653-e411de0da369> /Applications/OBS.app/Contents/Frameworks/QtCore.framework/Versions/A/QtCore
       0x102460000 -        0x102873fff com.obsproject.obs-studio (31.1.2) <fbe62454-6c8c-3153-ab12-ea95ebdda41a> /Applications/OBS.app/Contents/MacOS/OBS
       0x102b44000 -        0x102ba3fff dyld (*) <7e92b284-4b90-3b68-b31a-3ddc4c0e8d40> /usr/lib/dyld
       0x191874000 -        0x1918a9fff libsystem_kernel.dylib (*) <c8b3081a-5081-3a99-bbe3-01413de444c6> /usr/lib/system/libsystem_kernel.dylib
       0x1918aa000 -        0x1918b6fff libsystem_pthread.dylib (*) <ed328b18-eeef-3b15-8858-798b19b0c2cd> /usr/lib/system/libsystem_pthread.dylib
       0x102d74000 -        0x102e3bfff com.obsproject.libobs (31.1.2) <aa71c286-60cd-3b7c-b9ea-2d432ab73d5c> /Applications/OBS.app/Contents/Frameworks/libobs.framework/Versions/A/libobs
       0x191775000 -        0x1917f5fff libsystem_c.dylib (*) <00fc01c7-36bc-3193-86a3-5c03046b45fb> /usr/lib/system/libsystem_c.dylib
       0x12607c000 -        0x12613ffff obs-scripting.dylib (*) <6a065ca8-726b-30d2-af93-792af65a5296> /Applications/OBS.app/Contents/Frameworks/obs-scripting.dylib
       0x19a25f000 -        0x19a286fff com.apple.audio.caulk (1.0) <37a561f9-46f0-37fe-811b-894385645aed> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x127334000 -        0x127407fff net.nagater.obs-face-tracker (*) <103dc617-9814-31f9-b05b-c923d830f079> /Users/USER/Library/Application Support/obs-studio/*/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker
       0x19f141000 -        0x19f218fff com.apple.CoreMediaIO (1000.0) <a6d84343-7ca7-37ef-bcd8-4bc2f9b030d1> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
       0x19a287000 -        0x19a398fff com.apple.CoreMedia (1.0) <38594fcb-9201-3a72-a937-782d5126f374> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)
Writable regions: Total=2.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.1G(100%)

                                VIRTUAL   REGION
REGION TYPE                        SIZE    COUNT (non-coalesced)
===========                     =======  =======
Accelerate framework              1792K       14
Activity Tracing                   256K        1
CG backing stores                  768K        4
CG image                           464K       22
ColorSync                          560K       27
CoreAnimation                      336K       20
CoreGraphics                        64K        4
CoreUI image data                  800K       12
Foundation                          16K        1
Kernel Alloc Once                   32K        1
MALLOC                           717.3M      108
MALLOC guard page                  192K       10
MALLOC_MEDIUM (reserved)         664.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
OpenGL GLSL                        256K        3
STACK GUARD                       56.3M       21
Stack                             18.7M       23
VM_ALLOCATE                       48.4M       52
VM_ALLOCATE (reserved)           256.0M        2         reserved VM address space (unallocated)
__AUTH                            2634K      331
__AUTH_CONST                      20.0M      526
__CTF                               759        1
__DATA                            42.5M      604
__DATA_CONST                      30.8M      612
__DATA_DIRTY                      1809K      223
__FONT_DATA                          4K        1
__GLSLBUILTINS                    5176K        1
__LINKEDIT                       591.1M       85
__OBJC_CONST                      3703K      296
__OBJC_RO                         82.0M        1
__OBJC_RW                         3104K        1
__TEXT                           740.9M      630
__UNICODE                          588K        1
dyld private memory               1024K        1
mapped file                      474.2M       38
shared memory                      912K       16
===========                     =======  =======
TOTAL                              4.1G     3701
TOTAL, minus reserved VM space     2.8G     3701



-----------
Full Report
-----------

{"app_name":"OBS","timestamp":"2025-08-23 23:19:30.00 -0600","app_version":"31.1.2","slice_uuid":"fbe62454-6c8c-3153-ab12-ea95ebdda41a","build_version":"16531765140","platform":1,"bundleID":"com.obsproject.obs-studio","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C52)","incident_id":"724E07DC-4A31-4E03-8D12-9459E34C5BC3","name":"OBS"}
{
  "uptime" : 10000,
  "procLaunch" : "2025-08-23 20:23:54.9596 -0600",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Macmini9,1",
  "procStartAbsTime" : 1175655170,
  "coalitionID" : 654,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C52",
    "releaseType" : "User"
  },
  "captureTime" : "2025-08-23 23:19:27.1344 -0600",
  "incident" : "724E07DC-4A31-4E03-8D12-9459E34C5BC3",
  "bug_type" : "309",
  "pid" : 535,
  "procExitAbsTime" : 253946951252,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "OBS",
  "procPath" : "\/Applications\/OBS.app\/Contents\/MacOS\/OBS",
  "bundleInfo" : {"CFBundleShortVersionString":"31.1.2","CFBundleVersion":"16531765140","CFBundleIdentifier":"com.obsproject.obs-studio"},
  "storeInfo" : {"deviceIdentifierForVendor":"7309A335-ADA1-5317-B5E5-914AEF93FE5B","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.obsproject.obs-studio",
  "crashReporterKey" : "D29B9F53-7738-7F6B-D0E6-54670A12DDB2",
  "sip" : "enabled",
  "vmRegionInfo" : "0xffff800000000010 is not in any region.  Bytes after previous region: 18446497782568058897  \n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)\n--->  \n      UNUSED SPACE AT END",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x7ff0000000000010","rawCodes":[1,9218868437227405328],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x7ff0000000000010 -> 0xffff800000000010 (possible pointer authentication failure)"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":535},
  "vmregioninfo" : "0xffff800000000010 is not in any region.  Bytes after previous region: 18446497782568058897  \n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)\n--->  \n      UNUSED SPACE AT END",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":5174,"threadState":{"x":[{"value":5711320416},{"value":0},{"value":139432},{"value":4},{"value":262144},{"value":25},{"value":2048},{"value":0},{"value":105553129287744},{"value":9218868437227405312},{"value":2},{"value":73896},{"value":65537},{"value":5174},{"value":5174},{"value":8230404784,"symbolLocation":0,"symbol":"OBJC_CLASS_$_NSOpenGLContext"},{"value":8981340120},{"value":9102672016},{"value":4481482076},{"value":5739616768},{"value":5722216960},{"value":105553172199040},{"value":105553177952960},{"value":276},{"value":0},{"value":4340827744,"symbolLocation":224,"symbol":"_main_thread"},{"value":105553172314752},{"value":15},{"value":50331647}],"flavor":"ARM_THREAD_STATE64","lr":{"value":1692509039873716808},"cpsr":{"value":4096},"fp":{"value":6133766976},"sp":{"value":6133766944},"esr":{"value":2449473540,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":4912542288,"matchesCrashFrame":1},"far":{"value":9218868437227405328}},"queue":"com.apple.main-thread","frames":[{"imageOffset":29264,"symbol":"__gl_update_block_invoke","symbolLocation":92,"imageIndex":0},{"imageOffset":29256,"symbol":"__gl_update_block_invoke","symbolLocation":84,"imageIndex":0},{"imageOffset":7776,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":1},{"imageOffset":15276,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":1},{"imageOffset":73900,"symbol":"_dispatch_main_queue_callback_4CF","symbolLocation":944,"imageIndex":1},{"imageOffset":810752,"symbol":"__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__","symbolLocation":16,"imageIndex":2},{"imageOffset":538816,"symbol":"__CFRunLoopRun","symbolLocation":2540,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":208744,"symbol":"RunCurrentEventLoopInMode","symbolLocation":292,"imageIndex":3},{"imageOffset":208092,"symbol":"ReceiveNextEventCommon","symbolLocation":552,"imageIndex":3},{"imageOffset":207516,"symbol":"_BlockUntilNextEventMatchingListInModeWithFilter","symbolLocation":72,"imageIndex":3},{"imageOffset":269536,"symbol":"_DPSNextEvent","symbolLocation":844,"imageIndex":4},{"imageOffset":263556,"symbol":"-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]","symbolLocation":1332,"imageIndex":4},{"imageOffset":206244,"symbol":"-[NSApplication run]","symbolLocation":596,"imageIndex":4},{"imageOffset":91548,"imageIndex":5},{"imageOffset":634032,"symbol":"QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)","symbolLocation":596,"imageIndex":6},{"imageOffset":596504,"symbol":"QCoreApplication::exec()","symbolLocation":216,"imageIndex":6},{"imageOffset":1018908,"imageIndex":7},{"imageOffset":20724,"symbol":"start","symbolLocation":520,"imageIndex":8}]},{"id":5202,"name":"com.apple.CFSocket.private","frames":[{"imageOffset":48440,"symbol":"__select","symbolLocation":8,"imageIndex":9},{"imageOffset":717620,"symbol":"__CFSocketManager","symbolLocation":648,"imageIndex":2},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5203,"name":"libobs: hotkey thread","frames":[{"imageOffset":20672,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":9},{"imageOffset":30728,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":10},{"imageOffset":665400,"symbol":"os_event_timedwait","symbolLocation":128,"imageIndex":11},{"imageOffset":319800,"symbol":"obs_hotkey_thread","symbolLocation":168,"imageIndex":11},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5204,"name":"tiny_tubular_task_thread","frames":[{"imageOffset":6544,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":9},{"imageOffset":666044,"symbol":"os_sem_wait","symbolLocation":20,"imageIndex":11},{"imageOffset":659576,"symbol":"tiny_tubular_task_thread","symbolLocation":200,"imageIndex":11},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5212,"name":"audio-io: audio thread","frames":[{"imageOffset":20156,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":9},{"imageOffset":60808,"symbol":"nanosleep","symbolLocation":216,"imageIndex":12},{"imageOffset":60580,"symbol":"usleep","symbolLocation":68,"imageIndex":12},{"imageOffset":630368,"symbol":"os_sleepto_ns_fast","symbolLocation":100,"imageIndex":11},{"imageOffset":153108,"symbol":"audio_thread","symbolLocation":752,"imageIndex":11},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5233,"name":"video-io: video thread","frames":[{"imageOffset":6544,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":9},{"imageOffset":666044,"symbol":"os_sem_wait","symbolLocation":20,"imageIndex":11},{"imageOffset":169700,"symbol":"video_thread","symbolLocation":84,"imageIndex":11},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5234,"name":"libobs: graphics thread","frames":[{"imageOffset":20156,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":9},{"imageOffset":60808,"symbol":"nanosleep","symbolLocation":216,"imageIndex":12},{"imageOffset":630212,"symbol":"os_sleepto_ns","symbolLocation":96,"imageIndex":11},{"imageOffset":536152,"symbol":"obs_graphics_thread_loop","symbolLocation":6808,"imageIndex":11},{"imageOffset":204428,"symbol":"obs_graphics_thread_loop_autorelease","symbolLocation":32,"imageIndex":11},{"imageOffset":536944,"symbol":"obs_graphics_thread","symbolLocation":168,"imageIndex":11},{"imageOffset":204368,"symbol":"obs_graphics_thread_autorelease","symbolLocation":32,"imageIndex":11},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5235,"name":"scripting: defer","frames":[{"imageOffset":6544,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":9},{"imageOffset":666044,"symbol":"os_sem_wait","symbolLocation":20,"imageIndex":11},{"imageOffset":87072,"symbol":"defer_thread","symbolLocation":56,"imageIndex":13},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5244,"name":"AMCP Logging Spool","frames":[{"imageOffset":6544,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":9},{"imageOffset":129196,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":14},{"imageOffset":9820,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":14},{"imageOffset":8828,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":14},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5254,"name":"face-det","frames":[{"imageOffset":20672,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":9},{"imageOffset":30728,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":10},{"imageOffset":84988,"symbol":"face_detector_base::thread_routine(void*)","symbolLocation":160,"imageIndex":15},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5257,"frames":[{"imageOffset":20156,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":9},{"imageOffset":60808,"symbol":"nanosleep","symbolLocation":216,"imageIndex":12},{"imageOffset":60580,"symbol":"usleep","symbolLocation":68,"imageIndex":12},{"imageOffset":238948,"symbol":"CMIOGraph::OneOrMoreInputUnitsAreReadyToBePulled(bool&)","symbolLocation":732,"imageIndex":16},{"imageOffset":242052,"symbol":"CMIOGraph::DoWork(unsigned int)","symbolLocation":484,"imageIndex":16},{"imageOffset":253184,"symbol":"CMIO::Thread::QueuedTWorkThread<unsigned int>::DoWork()","symbolLocation":180,"imageIndex":16},{"imageOffset":287172,"symbol":"CMIO::Thread::SignaledThread::ThreadLoop()","symbolLocation":216,"imageIndex":16},{"imageOffset":286896,"symbol":"CMIO::Thread::SignaledThread::WorkQueuedThreadCallback(void*)","symbolLocation":88,"imageIndex":16},{"imageOffset":125576,"symbol":"figThreadMain","symbolLocation":248,"imageIndex":17},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5281,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6484,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":9},{"imageOffset":7424,"symbol":"mach_msg","symbolLocation":76,"imageIndex":9},{"imageOffset":544472,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":2},{"imageOffset":537488,"symbol":"__CFRunLoopRun","symbolLocation":1212,"imageIndex":2},{"imageOffset":534324,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":2},{"imageOffset":1764496,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":4},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5348,"name":"face-trk","frames":[{"imageOffset":20672,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":9},{"imageOffset":30728,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":10},{"imageOffset":304920,"symbol":"face_tracker_base::thread_routine(void*)","symbolLocation":188,"imageIndex":15},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":5391,"name":"face-trk","frames":[{"imageOffset":20672,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":9},{"imageOffset":30728,"symbol":"_pthread_cond_wait","symbolLocation":1228,"imageIndex":10},{"imageOffset":304920,"symbol":"face_tracker_base::thread_routine(void*)","symbolLocation":188,"imageIndex":15},{"imageOffset":29248,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":10},{"imageOffset":8228,"symbol":"thread_start","symbolLocation":8,"imageIndex":10}]},{"id":27833,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":27844,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":40274,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":47502,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":47503,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":63119,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]},{"id":77308,"frames":[{"imageOffset":8208,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":10}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4912513024,
    "size" : 278528,
    "uuid" : "361d1f0c-2786-3fd0-97e5-6da1abc7130b",
    "path" : "\/Applications\/OBS.app\/Contents\/Frameworks\/libobs-opengl.dylib",
    "name" : "libobs-opengl.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6734934016,
    "size" : 290816,
    "uuid" : "3a9e9a1e-72b6-3f66-aa17-d955384c1a39",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6737068032,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5521408,
    "uuid" : "f5ea9592-4ef9-3d35-b23d-5c21283acc52",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1856.105"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6883745792,
    "CFBundleShortVersionString" : "2.1.1",
    "CFBundleIdentifier" : "com.apple.HIToolbox",
    "size" : 3342336,
    "uuid" : "01b981b8-a2d8-374d-9a0e-c4ac8c1009da",
    "path" : "\/System\/Library\/Frameworks\/Carbon.framework\/Versions\/A\/Frameworks\/HIToolbox.framework\/Versions\/A\/HIToolbox",
    "name" : "HIToolbox"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6782775296,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15417344,
    "uuid" : "a8bbc643-113d-310f-96b6-77a973bf2dba",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.20.111"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4472799232,
    "size" : 671744,
    "uuid" : "62b55791-da21-30f4-946f-7cb71ad0de1a",
    "path" : "\/Applications\/OBS.app\/Contents\/PlugIns\/platforms\/libqcocoa.dylib",
    "name" : "libqcocoa.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4378050560,
    "CFBundleShortVersionString" : "6.8",
    "CFBundleIdentifier" : "org.qt-project.QtCore",
    "size" : 4816896,
    "uuid" : "35642b16-7f41-3e13-a653-e411de0da369",
    "path" : "\/Applications\/OBS.app\/Contents\/Frameworks\/QtCore.framework\/Versions\/A\/QtCore",
    "name" : "QtCore",
    "CFBundleVersion" : "6.8.3"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4333109248,
    "CFBundleShortVersionString" : "31.1.2",
    "CFBundleIdentifier" : "com.obsproject.obs-studio",
    "size" : 4276224,
    "uuid" : "fbe62454-6c8c-3153-ab12-ea95ebdda41a",
    "path" : "\/Applications\/OBS.app\/Contents\/MacOS\/OBS",
    "name" : "OBS",
    "CFBundleVersion" : "16531765140"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4340334592,
    "size" : 393216,
    "uuid" : "7e92b284-4b90-3b68-b31a-3ddc4c0e8d40",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6736527360,
    "size" : 221184,
    "uuid" : "c8b3081a-5081-3a99-bbe3-01413de444c6",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6736748544,
    "size" : 53248,
    "uuid" : "ed328b18-eeef-3b15-8858-798b19b0c2cd",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342628352,
    "CFBundleShortVersionString" : "31.1.2",
    "CFBundleIdentifier" : "com.obsproject.libobs",
    "size" : 819200,
    "uuid" : "aa71c286-60cd-3b7c-b9ea-2d432ab73d5c",
    "path" : "\/Applications\/OBS.app\/Contents\/Frameworks\/libobs.framework\/Versions\/A\/libobs",
    "name" : "libobs",
    "CFBundleVersion" : "16531765140"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6735482880,
    "size" : 528384,
    "uuid" : "00fc01c7-36bc-3193-86a3-5c03046b45fb",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4933009408,
    "size" : 802816,
    "uuid" : "6a065ca8-726b-30d2-af93-792af65a5296",
    "path" : "\/Applications\/OBS.app\/Contents\/Frameworks\/obs-scripting.dylib",
    "name" : "obs-scripting.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6881144832,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 163840,
    "uuid" : "37a561f9-46f0-37fe-811b-894385645aed",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4952637440,
    "CFBundleShortVersionString" : "",
    "CFBundleIdentifier" : "net.nagater.obs-face-tracker",
    "size" : 868352,
    "uuid" : "103dc617-9814-31f9-b05b-c923d830f079",
    "path" : "\/Users\/USER\/Library\/Application Support\/obs-studio\/*\/obs-face-tracker.plugin\/Contents\/MacOS\/obs-face-tracker",
    "name" : "obs-face-tracker",
    "CFBundleVersion" : ""
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6963859456,
    "CFBundleShortVersionString" : "1000.0",
    "CFBundleIdentifier" : "com.apple.CoreMediaIO",
    "size" : 884736,
    "uuid" : "a6d84343-7ca7-37ef-bcd8-4bc2f9b030d1",
    "path" : "\/System\/Library\/Frameworks\/CoreMediaIO.framework\/Versions\/A\/CoreMediaIO",
    "name" : "CoreMediaIO",
    "CFBundleVersion" : "5352.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6881308672,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.CoreMedia",
    "size" : 1122304,
    "uuid" : "38594fcb-9201-3a72-a937-782d5126f374",
    "path" : "\/System\/Library\/Frameworks\/CoreMedia.framework\/Versions\/A\/CoreMedia",
    "name" : "CoreMedia",
    "CFBundleVersion" : "2930.8.1.4.1"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6733578240,
  "size" : 3089596416,
  "uuid" : "66c33c62-48a9-31e5-b8b5-7a71c9760d07"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.3G resident=0K(0%) swapped_out_or_unallocated=1.3G(100%)\nWritable regions: Total=2.1G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=2.1G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework              1792K       14 \nActivity Tracing                   256K        1 \nCG backing stores                  768K        4 \nCG image                           464K       22 \nColorSync                          560K       27 \nCoreAnimation                      336K       20 \nCoreGraphics                        64K        4 \nCoreUI image data                  800K       12 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           717.3M      108 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         664.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nOpenGL GLSL                        256K        3 \nSTACK GUARD                       56.3M       21 \nStack                             18.7M       23 \nVM_ALLOCATE                       48.4M       52 \nVM_ALLOCATE (reserved)           256.0M        2         reserved VM address space (unallocated)\n__AUTH                            2634K      331 \n__AUTH_CONST                      20.0M      526 \n__CTF                               759        1 \n__DATA                            42.5M      604 \n__DATA_CONST                      30.8M      612 \n__DATA_DIRTY                      1809K      223 \n__FONT_DATA                          4K        1 \n__GLSLBUILTINS                    5176K        1 \n__LINKEDIT                       591.1M       85 \n__OBJC_CONST                      3703K      296 \n__OBJC_RO                         82.0M        1 \n__OBJC_RW                         3104K        1 \n__TEXT                           740.9M      630 \n__UNICODE                          588K        1 \ndyld private memory               1024K        1 \nmapped file                      474.2M       38 \nshared memory                      912K       16 \n===========                     =======  ======= \nTOTAL                              4.1G     3701 \nTOTAL, minus reserved VM space     2.8G     3701 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000614
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    },
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "621d4d0f680160486b9e1c98"
      },
      "deploymentId" : 240000416
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "61fb0e87c773c43cde3bb80e"
      },
      "deploymentId" : 240000305
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 240000492
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000083
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by dansternofbeyer** [comment]
Sorry this turned into a super long thread. Let me know if there's another way to post the crash reports.
And I am super thankful for you looking into this! If you can fix this bug it will make this art installation possible. Thank you!

**Comment by dansternofbeyer** [comment]
Okay! Thank you so much for answering all of these questions! I have good news and some more questions.

First, good news! I had the Face Tracker watch Office Space 6 times in a row and it did not crash. Amazing. I believe the crashes were happening because of the sleep function, and once that was turned off, it worked like a charm.

Second, I'm using the shape_predictor_5_face_landmarks.dat model because, although no-one is making any profit from this art installation (in fact it's going to cost us), there is money involved. And this model is working really well. I've set the Track Kp to 10 and it snaps!

Question : is there a way to deal with faces TILTING? It tracks a titled face, but does not keep the face square in the frame.

Third, I'd like to share with you what we are trying to do! Year ago, our little public art team made a huge sculptural face, and let folks sit in front of a webcam to have thier face projected onto the Big Face. Everyone loves this, even tho they look terrible. It's really funny and fun. However, it was always a challenge to get peoples face in the 'correct' place to line up with the sculptural face. But! Thanks to your amazing software, this can happen automatically, making the interactivity so much easier and even more fun. Thank you! Here's a link to the old installation : https://www.newamericanpublicart.com/yourbigface

We have been commissioned to install the Big Face at an art show in Arizona in November https://scottsdalearts.org/explore-scottsdale-arts/canal-convergence/

We are so excited to use this software to improve the interactivity of the installation.

We really want to highlight and credit you for this! How would you like to be documented and linked? We want more people knowing about your incredible work.

**Comment by norihiro** [comment]
I'm implementing the rotation when a person tilts their face on this branch.
- https://github.com/norihiro/obs-face-tracker/tree/feature/rotate

Hopefully, I can release it soon.

**Comment by norihiro** [comment]
Hi @dansternofbeyer,

The feature to rotate the face is ready so that the tilting face will be adjusted.
The angle is detected by the location of the eyeballs so that you need to enable 5-point or 68-point facial landmark detection.

- https://github.com/norihiro/obs-face-tracker/releases/tag/0.8.0-rotate1
  - Direct link for Apple Silicon: [PKG](https://github.com/norihiro/obs-face-tracker/releases/download/0.8.0-rotate1/obs-face-tracker-0.8.0-rotate1-obs30-macos-arm64.pkg), [ZIP](https://github.com/norihiro/obs-face-tracker/releases/download/0.8.0-rotate1/obs-face-tracker-0.8.0-rotate1-obs30-macos-arm64.zip)

I hope this will be helpful for your exhibition.
Please feel free to let me know if something is wrong or need something.

Best Regards,
Norihiro Kamae

**Comment by norihiro** [comment]
I'm sorry that there is a mistake in the release script. The released package did not contain the necessary library `libopenblas.0.dylib`.

I fixed the package.
- https://github.com/norihiro/obs-face-tracker/releases/tag/0.8.1-rotate1
- Direct link: [PKG](https://github.com/norihiro/obs-face-tracker/releases/download/0.8.1-rotate1/obs-face-tracker-0.8.1-rotate1-obs30-macos-arm64.pkg), [ZIP](https://github.com/norihiro/obs-face-tracker/releases/download/0.8.1-rotate1/obs-face-tracker-0.8.1-rotate1-obs30-macos-arm64.zip).

**Comment by dansternofbeyer** [comment]
I am still getting the same message when I start OBS. Which states that the plugin cannot be loaded.

Here is the log

08:15:41.698: [macOS] Permission for audio device access granted.
08:15:41.700: [macOS] Permission for video device access granted.
08:15:41.700: [macOS] Permission for input monitoring denied.
08:15:41.703: [macOS] Permission for screen capture granted.
08:15:41.703: CPU Name: Apple M4 Max
08:15:41.703: Physical Cores: 16, Logical Cores: 16
08:15:41.703: Physical Memory: 131072MB Total
08:15:41.703: Model Identifier: Mac16,5
08:15:41.703: OS Name: macOS
08:15:41.703: OS Version: Version 15.1 (Build 24B2083)
08:15:41.703: Rosetta translation used: false
08:15:41.703: Kernel Version: 24.1.0
08:15:41.704: [hotkeys-cocoa]: No event permissions, could not add global hotkeys.
08:15:41.704: hotkeys-cocoa: Using keyboard layout 'com.apple.keylayout.US'
08:15:41.704: Current Date/Time: 2025-10-06, 08:15:41
08:15:41.704: Browser Hardware Acceleration: true
08:15:41.704: Qt Version: 6.8.3 (runtime), 6.8.3 (compiled)
08:15:41.704: Portable mode: false
08:15:41.797: OBS 32.0.1 (mac)
08:15:41.797: ---------------------------------
08:15:41.798: ---------------------------------
08:15:41.798: audio settings reset:
08:15:41.798: 	samples per sec: 48000
08:15:41.798: 	speakers:        2
08:15:41.798: 	max buffering:   960 milliseconds
08:15:41.798: 	buffering type:  dynamically increasing
08:15:41.799: ---------------------------------
08:15:41.799: Initializing OpenGL...
08:15:41.824: Loading up OpenGL on adapter Apple Apple M4 Max
08:15:41.825: OpenGL loaded successfully, version 4.1 Metal - 89.3, shading language 4.10
08:15:41.934: ---------------------------------
08:15:41.934: video settings reset:
08:15:41.934: 	base resolution:   1920x1080
08:15:41.934: 	output resolution: 1920x1080
08:15:41.934: 	downscale filter:  Bicubic
08:15:41.934: 	fps:               60/1
08:15:41.934: 	format:            NV12
08:15:41.934: 	YUV mode:          Rec. 709/Partial
08:15:41.934: NV12 texture support enabled
08:15:41.934: P010 texture support not available
08:15:41.944: Audio monitoring device:
08:15:41.944: 	name: Default
08:15:41.944: 	id: default
08:15:41.945: ---------------------------------
08:15:41.947: No AJA devices found, skipping loading AJA UI plugin
08:15:41.947: Failed to initialize module 'aja-output-ui'
08:15:41.949: No AJA devices found, skipping loading AJA plugin
08:15:41.949: Failed to initialize module 'aja'
08:15:41.950: Failed to load 'en-US' text for module: 'decklink-captions'
08:15:41.950: Failed to load 'en-US' text for module: 'decklink-output-ui'
08:15:41.950: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
08:15:41.950: Failed to initialize module 'decklink'
08:15:42.048: [obs-browser]: Version 2.26.2
08:15:42.049: [obs-browser]: CEF Version 127.0.6533.120 (runtime), 127.0.0-6533-fix-stutter.3039+g2b7d20b+chromium-127.0.6533.120 (compiled)
08:15:42.055: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.6.3 | RPC Version: 1)
08:15:42.055: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.8.3 | Qt version (run-time): 6.8.3
08:15:42.055: [obs-websocket] [obs_module_load] Linked ASIO Version: 103200
08:15:42.057: [obs-websocket] [obs_module_load] Module loaded.
08:15:42.060: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 0x0106): tried: '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (no such file), '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/VLC.app/Contents/MacOS/lib/libvlccore.9.dylib' (no such file), '/Applications/VLC.app/Contents/MacOS/lib/libvlccore.9.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
08:15:42.060: 
08:15:42.060: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
08:15:42.060: os_dlopen(/Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker->/Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker): dlopen(/Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker, 0x0106): Library not loaded: @rpath/libgcc_s.1.1.dylib
08:15:42.060:   Referenced from: <ED5A5014-F830-3897-9159-3CC545E4DFFA> /Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/lib/libgfortran.5.dylib
08:15:42.060:   Reason: tried: '/Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/lib/libgcc_s.1.1.dylib' (no such file), '/Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/lib/libgcc_s.1.1.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/gcc/aarch64-apple-darwin23/15/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gcc/lib/gcc/current/gcc/aarch64-apple-darwin23/15/libgcc_s.1.1.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/gcc/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gcc/lib/gcc/current/gcc/libgcc_s.1.1.dylib' (no such file), '/opt/homebrew/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gcc/lib/gcc/current/libgcc_s.1.1.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libgcc_s.1.1.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libgcc_s.1.1.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libgcc_s.1.1.dylib' (no such file), '/Applications/OBS.app/Contents/Frameworks/libgcc_s.1.1.dylib' (no such file)
08:15:42.060: 
08:15:42.060: Module '/Users/garyschmid/Library/Application Support/obs-studio/plugins/obs-face-tracker.plugin/Contents/MacOS/obs-face-tracker' not loaded
08:15:42.060: ---------------------------------
08:15:42.060:   Loaded Modules:
08:15:42.060:     vlc-video
08:15:42.060:     text-freetype2
08:15:42.060:     rtmp-services
08:15:42.060:     obs-x264
08:15:42.060:     obs-websocket
08:15:42.060:     obs-webrtc
08:15:42.060:     obs-vst
08:15:42.060:     obs-transitions
08:15:42.060:     obs-outputs
08:15:42.060:     obs-filters
08:15:42.060:     obs-ffmpeg
08:15:42.060:     obs-browser
08:15:42.060:     mac-virtualcam
08:15:42.060:     mac-videotoolbox
08:15:42.060:     mac-syphon
08:15:42.060:     mac-capture
08:15:42.060:     mac-avcapture
08:15:42.060:     mac-avcapture-legacy
08:15:42.060:     image-source
08:15:42.060:     frontend-tools
08:15:42.060:     decklink-output-ui
08:15:42.060:     decklink-captions
08:15:42.060:     coreaudio-encoder
08:15:42.060: ---------------------------------
08:15:42.060: [VideoToolbox encoder]: Added VideoToolbox encoders
08:15:42.061: ---------------------------------
08:15:42.061: Available Encoders:
08:15:42.061:   Video Encoders:
08:15:42.061: 	- ffmpeg_aom_av1 (AOM AV1)
08:15:42.061: 	- obs_x264 (x264)
08:15:42.061: 	- com.apple.videotoolbox.videoencoder.prores-422 (Apple VT ProRes Software Encoder)
08:15:42.061: 	- com.apple.videotoolbox.videoencoder.appleproreshw.422 (Apple VT ProRes Hardware Encoder)
08:15:42.061: 	- com.apple.videotoolbox.videoencoder.ave.avc (Apple VT H264 Hardware Encoder)
08:15:42.061: 	- com.apple.videotoolbox.videoencoder.h264 (Apple VT H264 Software Encoder)
08:15:42.061: 	- com.apple.videotoolbox.videoencoder.ave.hevc (Apple VT HEVC Hardware Encoder)
08:15:42.061: 	- com.apple.videotoolbox.videoencoder.hevc.vcp (Apple VT HEVC Software Encoder)
08:15:42.061:   Audio Encoders:
08:15:42.061: 	- CoreAudio_AAC (CoreAudio AAC)
08:15:42.061: 	- ffmpeg_aac (FFmpeg AAC)
08:15:42.061: 	- ffmpeg_opus (FFmpeg Opus)
08:15:42.061: 	- ffmpeg_pcm_s16le (FFmpeg PCM (16-bit))
08:15:42.061: 	- ffmpeg_pcm_s24le (FFmpeg PCM (24-bit))
08:15:42.061: 	- ffmpeg_pcm_f32le (FFmpeg PCM (32-bit float))
08:15:42.061: 	- ffmpeg_alac (FFmpeg ALAC (24-bit))
08:15:42.061: 	- ffmpeg_flac (FFmpeg FLAC (16-bit))
08:15:42.061: ==== Startup complete ===============================================
08:15:42.066: signal_handler_connect: signal 'file_changed' not found
08:15:42.101: All scene data cleared
08:15:42.101: ------------------------------------------------
08:15:42.105: Switched to scene 'Scene'
08:15:42.105: ------------------------------------------------
08:15:42.105: Loaded scenes:
08:15:42.105: - scene 'Scene':
08:15:42.105:     - source: 'Video Capture Device' (macos-avcapture)
08:15:42.105: ------------------------------------------------
08:15:42.159: Video Capture Device: Selected device 'MacBook Pro Camera'
08:15:42.210: [mac-virtualcam] macOS Camera Extension activated successfully.
